import type { ClueDef, LocationDef } from "./types";

export const TITLE = "Three Colors of Madness";

export const SPINE = [
  "no-exit",
  "six-club",
  "maternal",
  "ophion-name",
  "insurance",
];

export const CLUES: Record<string, ClueDef> = {
  "no-exit": {
    id: "no-exit",
    title: "No exit wound",
    fact: "Each clubman bears a single hole above the bridge of the nose. Nothing answers it at the back of the skull. No powder. No pool.",
    unstable: "Each of them asked a bullet to arrive, and it obliged, and troubled itself with nothing else.",
    boardColumn: "club",
    required: true,
  },
  wexford: {
    id: "wexford",
    title: "Judge Absalom Wexford",
    fact: "Forty years on the county bench. Sent Walter's father to the workhouse once for public drunkenness.",
    boardColumn: "club",
  },
  fenn: {
    id: "fenn",
    title: "Dr. Aldous Fenn",
    fact: "Signed Constance Corwin's death certificate not eleven months prior. A private library with a book left unlocked.",
    unstable: "Fenn did not fear death. He feared being left behind.",
    boardColumn: "club",
  },
  corliss: {
    id: "corliss",
    title: "District Attorney Miles Corliss",
    fact: "Shook Walter's hand at the Policemen's Benevolent dinner and called him a credit to the badge.",
    boardColumn: "club",
  },
  kessler: {
    id: "kessler",
    title: "Otto Kessler, butcher",
    fact: "Shop on Pickman Street. His boning knife, wiped too clean, tucked under a hedge root.",
    boardColumn: "club",
  },
  pruitt: {
    id: "pruitt",
    title: "Josiah Pruitt",
    fact: "Land and mills and deeds. The kind of fortune that spends half its life proving it owns the other half.",
    boardColumn: "club",
  },
  unknown: {
    id: "unknown",
    title: "Unknown male, club dress",
    fact: "Approx. 50–60. No calling card, no monogram, watch stopped at 3:17, maker's plate filed smooth. The club's rolls do not contain a sixth name.",
    boardColumn: "club",
    required: true,
  },
  "six-club": {
    id: "six-club",
    title: "Six members",
    fact: "The club numbers six. The garden holds six men in evening dress. Five named. One never is.",
    boardColumn: "club",
    required: true,
  },
  birches: {
    id: "birches",
    title: "Woman and boy, beyond the birches",
    fact: "Clothes poor but not destitute. Not a single clean motion. Officially: transients. Walter wrote the word in under a minute.",
    boardColumn: "victims",
    required: true,
  },
  eight: {
    id: "eight",
    title: "Eight people are dead",
    fact: "Odell: six members are dead. The other two are a filing matter. Walter wrote EIGHT in a hand larger than usual.",
    boardColumn: "town",
  },
  naomi: {
    id: "naomi",
    title: "Naomi Freeman",
    fact: "Came north looking for a cousin, then for documentation of wages owed a whaling ancestor. A lay, unpaid. An older boy who did not come north: Ekon.",
    boardColumn: "victims",
  },
  "ophion-name": {
    id: "ophion-name",
    title: "They named the club after the ship",
    fact: "Father Behan: they came to believe the ship had been chosen. It wasn't. Men inherit money and then invent a reason they deserved it.",
    boardColumn: "club",
    required: true,
  },
  insurance: {
    id: "insurance",
    title: "Ordinary, well-documented fraud",
    fact: "A Wexford estate purchased within eighteen months of a fleet's loss. A Corliss mill the same season. Pruitt land before the underwriters' ink had dried. Crew lists: Freeman, then again, then not at all.",
    boardColumn: "town",
    required: true,
  },
  maternal: {
    id: "maternal",
    title: "They started speaking, tenderly, of her",
    fact: "Kessler, more than once: she'll have us home. She's no different from any mother.",
    unstable: "They stopped speaking of power, toward the end.",
    boardColumn: "club",
    required: true,
  },
  knife: {
    id: "knife",
    title: "Kessler's knife",
    fact: "Wiped too clean. Tucked under a hedge root. Never in its life used on a hog.",
    boardColumn: "club",
  },
  tunnel: {
    id: "tunnel",
    title: "A stair that appears on no floor plan",
    fact: "Worked stone, then rock. Two kinds of remains. Force delays one. May end the other.",
    boardColumn: "below",
  },
  book: {
    id: "book",
    title: "A passage copied, not stolen",
    fact: "A minor, largely discredited figure from old cosmogony. A serpent who ruled before being cast down, not destroyed. Walter left the book on Fenn's shelf.",
    boardColumn: "below",
  },
  maid: {
    id: "maid",
    title: "A kitchen maid, previously vanished",
    fact: "Pruitt employed her despite his own signed denial. Walter had given the landowner's word the benefit he withheld from hers.",
    boardColumn: "town",
  },
};

export const PROLOGUE = [
  {
    kicker: "Widow's Bight Historical Society  ·  A Civic Reel",
    title: "A fleet went out",
    body: "Roughly a century ago a whaling fleet left this harbor and did not fully come home. The survivors who returned could never tell the same account of what happened twice. The town recorded the loss as weather, and closed the book.",
    img: "/game/harbor-civic.jpg",
  },
  {
    kicker: "From the underwriters' own abstracts",
    title: "Money found its way",
    body: "A great deal of insurance money nonetheless found its way into a small number of hands. Those hands became the town's ruling families. The town has never had to examine any of this.",
    img: "/game/town-dusk.jpg",
  },
  {
    kicker: "The Ophion Club, est. in memory of the fleet",
    title: "An honorific",
    body: "Decades after the wreck, a private society was founded and named for the lost flagship. The club is exclusive on the premise that everyone in it paid a price with their lives — a claim that was true only of the crew, never of the club.",
    img: "/game/club-night.jpg",
  },
];

export const LOCATIONS: LocationDef[] = [
  {
    id: "drive",
    chapter: 1,
    name: "The drive",
    set: "drive",
    spawn: [0, 1.7, 16],
    yaw: 0,
    fog: "#5a5a56",
    fogNear: 14,
    fogFar: 72,
    ambient: "#2a241c",
    iris: "square",
    floor: "gravel",
    bounds: { minX: -8, maxX: 8, minZ: -22, maxZ: 20 },
    walls: [
      { minX: -9, maxX: -7.4, minZ: -22, maxZ: 20 },
      { minX: 7.4, maxX: 9, minZ: -22, maxZ: 20 },
      { minX: -8, maxX: 8, minZ: -23.5, maxZ: -21.2 },
    ],
    interactables: [
      {
        id: "boy",
        pos: [3.2, 1.2, 8],
        label: "Gatehouse boy",
        kind: "person",
        radius: 2.4,
        options: [
          {
            id: "ask",
            label: "Wait",
            result: {
              lines: [
                { text: "THEY'RE IN THE ROSE GARDEN, OFFICER. WHAT'S LEFT OF THEM." },
              ],
              flag: "gardenOpen",
              unlock: "gardenOpen",
            },
          },
        ],
      },
      {
        id: "to-garden",
        pos: [0, 1, -18],
        label: "The rose garden",
        kind: "exit",
        exitTo: "garden",
        requireFlag: "gardenOpen",
        radius: 2.8,
      },
      {
        id: "lantern-post",
        pos: [-2.2, 1, 4],
        label: "Lantern",
        kind: "examine",
        title: "A club lantern",
        body: "The flame is trimmed low, as if whoever last passed here did not intend to be seen coming back.",
        radius: 1.6,
      },
    ],
  },
  {
    id: "garden",
    chapter: 1,
    name: "The rose garden",
    set: "garden",
    spawn: [0, 1.7, 12],
    fog: "#4e4e4c",
    fogNear: 12,
    fogFar: 58,
    ambient: "#181410",
    iris: "open",
    floor: "grass",
    bounds: { minX: -16, maxX: 16, minZ: -16, maxZ: 16 },
    interactables: [
      {
        id: "wexford",
        pos: [-4.2, 0.4, -1.2],
        label: "Judge Wexford",
        kind: "examine",
        title: "Judge Absalom Wexford",
        body: "A single black hole above the bridge of the nose, precise as a coin pressed into wax. No powder scorched the collar. When the head is turned, there is no wound at the back of the skull to answer the one in front.",
        clueId: "wexford",
        perception: 8,
        radius: 1.8,
      },
      {
        id: "fenn-body",
        pos: [-1.6, 0.4, -2.4],
        label: "Dr. Fenn",
        kind: "examine",
        title: "Dr. Aldous Fenn",
        body: "He signed your mother's death certificate not eleven months prior. The same hole. The same absence of an exit. Evening dress, as if the meeting had only just been called to order.",
        clueId: "fenn",
        perception: 6,
        radius: 1.8,
      },
      {
        id: "corliss-body",
        pos: [1.2, 0.4, -2.6],
        label: "D.A. Corliss",
        kind: "examine",
        title: "District Attorney Miles Corliss",
        body: "He shook your hand at the Policemen's Benevolent dinner. A credit to the badge, he said. The bullet, if that is the word, arrived without asking the rest of the skull for an opinion.",
        clueId: "corliss",
        perception: 5,
        radius: 1.8,
      },
      {
        id: "kessler-body",
        pos: [3.8, 0.4, -1.6],
        label: "Otto Kessler",
        kind: "examine",
        title: "Otto Kessler",
        body: "The butcher. More trade than any three shops combined. His good coat is on him. His good knife is not.",
        clueId: "kessler",
        perception: 5,
        radius: 1.8,
      },
      {
        id: "pruitt-body",
        pos: [5.2, 0.4, 0.6],
        label: "Josiah Pruitt",
        kind: "examine",
        title: "Josiah Pruitt",
        body: "Land and mills and deeds. You place the face by reputation before you place it by name. Same hole. Same empty back of the head.",
        clueId: "pruitt",
        perception: 5,
        radius: 1.8,
      },
      {
        id: "sixth",
        pos: [-5.4, 0.4, 0.8],
        label: "Unknown man",
        kind: "examine",
        title: "Unknown male, approx. 50–60, club dress",
        body: "Nothing that wants to be found: no calling card, no monogrammed cuff, no wallet. A watch, stopped at seventeen past three, its maker's plate filed smooth. Some blanks in a case file are not oversights.",
        clueId: "unknown",
        perception: 8,
        radius: 1.8,
      },
      {
        id: "knife",
        pos: [4.6, 0.2, 2.4],
        label: "Something under the hedge",
        kind: "pickup",
        title: "A boning knife",
        body: "Wiped too clean. Tucked under a hedge root. You bag it. You tag it. You do not yet understand that some blanks are load-bearing.",
        clueId: "knife",
        item: "knife",
        perception: 5,
        hideIfExamined: true,
        radius: 1.5,
      },
      {
        id: "birches",
        pos: [-11, 0.4, -8],
        label: "Past the birches",
        kind: "examine",
        title: "A woman and a boy",
        body: "Clothes poor but not destitute — the coat too light for the season, the boy's shoes resoled twice. Whatever was done was not done with a single clean motion. You look once. You write unidentified, and you do not look again.",
        clueId: "birches",
        perception: 8,
        radius: 2.2,
      },
      {
        id: "no-exit-note",
        pos: [0, 0.3, -0.2],
        label: "The half-circle",
        kind: "examine",
        title: "Six men in evening dress",
        body: "They lie in a half-circle behind the clipped hedges. No blood ran anywhere it should have pooled. As if the bullet had simply been asked to arrive there, and had obliged.",
        clueId: "no-exit",
        perception: 6,
        radius: 2.4,
      },
      {
        id: "odell",
        pos: [2.4, 1.1, 8.5],
        label: "Captain Odell",
        kind: "person",
        radius: 2.2,
        options: [
          {
            id: "report",
            label: "Show him the notes",
            result: {
              lines: [
                { speaker: "Odell", text: "GAS-MAIN TRAGEDY." },
                { speaker: "You write", text: "NO BURNS." },
                { speaker: "You write", text: "NO EXIT WOUNDS." },
                { speaker: "Odell", text: "Six. Not eight." },
              ],
              clueId: "six-club",
              perception: 6,
              flag: "odell",
            },
          },
          {
            id: "eight",
            label: "Eight people are dead",
            result: {
              lines: [
                { speaker: "You", text: "Eight people are dead." },
                { speaker: "Odell", text: "Six members are dead. The other two are a filing matter. You understand the difference." },
              ],
              clueId: "eight",
              perception: 6,
              flag: "eightOffered",
            },
          },
        ],
      },
      {
        id: "to-street",
        pos: [0, 1, 14.5],
        label: "Leave for town",
        kind: "exit",
        exitTo: "street",
        radius: 2.2,
      },
    ],
  },
  {
    id: "street",
    chapter: 1,
    name: "Pickman Street",
    set: "street",
    spawn: [0, 1.7, 6],
    fog: "#0d0c0b",
    fogNear: 5,
    fogFar: 30,
    ambient: "#161310",
    iris: "open",
    floor: "gravel",
    bounds: { minX: -18, maxX: 18, minZ: -10, maxZ: 12 },
    interactables: [
      {
        id: "door-morgue",
        pos: [-12, 1, -6],
        label: "County morgue",
        kind: "exit",
        exitTo: "morgue",
        radius: 2,
      },
      {
        id: "door-precinct",
        pos: [-6, 1, -6],
        label: "Precinct",
        kind: "exit",
        exitTo: "precinct",
        radius: 2,
      },
      {
        id: "door-almy",
        pos: [0, 1, -6],
        label: "Mrs. Almy's boardinghouse",
        kind: "exit",
        exitTo: "almy",
        radius: 2,
      },
      {
        id: "door-archive",
        pos: [6, 1, -6],
        label: "Town archive",
        kind: "exit",
        exitTo: "archive",
        radius: 2,
      },
      {
        id: "door-rectory",
        pos: [12, 1, -6],
        label: "The rectory",
        kind: "exit",
        exitTo: "rectory",
        radius: 2,
      },
      {
        id: "door-bar",
        pos: [-8, 1, 8],
        label: "Ophion Club service entrance",
        kind: "exit",
        exitTo: "bar",
        radius: 2,
      },
      {
        id: "door-room",
        pos: [4, 1, 8],
        label: "Your room above the cobbler",
        kind: "exit",
        exitTo: "room",
        radius: 2,
      },
      {
        id: "door-fenn",
        pos: [10, 1, 8],
        label: "Fenn's house",
        kind: "exit",
        exitTo: "library",
        radius: 2,
      },
      {
        id: "widow",
        pos: [-4, 1.1, 2],
        label: "Kessler's widow",
        kind: "person",
        radius: 2,
        options: [
          {
            id: "badge",
            label: "Speak as the badge",
            requireCoat: "uniform",
            result: {
              lines: [
                { text: "SHE WANTS TO KNOW HOW SHOP MONEY BOUGHT A CHAIR AMONG MEN WHO CALLED HIM TRADESMAN TO HIS FACE." },
                { text: "Odell is already steering her toward the door." },
              ],
              perception: 3,
            },
          },
          {
            id: "plain",
            label: "Come back without the badge",
            requireCoat: "plain",
            result: {
              lines: [
                { text: "SHE CRIES. SHE TELLS YOU THINGS SHE WOULD NEVER HAVE TOLD A BADGE." },
                { text: "HE WORE HIS GOOD COAT TO A CLUB THAT USED HIM AND DESPISED HIM IN THE SAME EVENING." },
              ],
              perception: 6,
              flag: "widowPlain",
            },
          },
        ],
      },
      {
        id: "observer",
        pos: [14, 1.1, 1],
        label: "A quarryman",
        kind: "person",
        radius: 2,
        options: [
          {
            id: "look",
            label: "He will not meet the frame",
            result: {
              lines: [
                { text: "HIS FIRE IS THE COLOR OF ASH. A RING ON HIS HAND CATCHES A COLOR THE REST OF THE STREET DOES NOT HAVE." },
                { text: "HE DOES NOT LOOK AT YOU FOR LONG. HE DOES NOT LOOK AT THE CLUB AT ALL." },
              ],
              perception: 4,
              flag: "observer1",
            },
          },
        ],
      },
    ],
  },
  {
    id: "morgue",
    chapter: 1,
    name: "County morgue",
    set: "interior",
    spawn: [0, 1.7, 4],
    fog: "#0a0908",
    fogNear: 8,
    fogFar: 22,
    ambient: "#12100e",
    iris: "open",
    floor: "stone",
    bounds: { minX: -6, maxX: 6, minZ: -6, maxZ: 6 },
    walls: [
      { minX: -6.2, maxX: -5.6, minZ: -6, maxZ: 6 },
      { minX: 5.6, maxX: 6.2, minZ: -6, maxZ: 6 },
      { minX: -6, maxX: 6, minZ: -6.2, maxZ: -5.6 },
    ],
    interactables: [
      {
        id: "coroner",
        pos: [0, 1.1, -2],
        label: "The coroner",
        kind: "person",
        radius: 2.2,
        options: [
          {
            id: "why",
            label: "Why is there no exit wound",
            result: {
              lines: [
                { speaker: "You write", text: "WHY IS THERE NO EXIT WOUND, DOCTOR." },
                { text: "He opens Wexford's skull a second time as though a different answer might be hiding. Nothing changes. He writes nothing on the sheet." },
                { text: "This is not a man withholding a diagnosis. This is a man who has simply run out of profession before he ran out of body." },
              ],
              clueId: "no-exit",
              perception: 8,
              flag: "coroner",
            },
          },
        ],
      },
      {
        id: "sheets",
        pos: [-3, 0.8, -1],
        label: "Sheeted tables",
        kind: "examine",
        title: "Six tables. Two empty.",
        body: "The row is already the shape Odell wants. The birches will not appear in it. They will simply not be in it, the way a fact that has never been recorded is not technically a lie.",
        clueId: "six-club",
        perception: 4,
        radius: 1.8,
      },
      {
        id: "leave-morgue",
        pos: [0, 1, 5.4],
        label: "Street",
        kind: "exit",
        exitTo: "street",
        radius: 1.8,
      },
    ],
  },
  {
    id: "precinct",
    chapter: 1,
    name: "The precinct",
    set: "interior",
    spawn: [0, 1.7, 4],
    fog: "#0c0b0a",
    fogNear: 10,
    fogFar: 24,
    ambient: "#141210",
    iris: "open",
    floor: "wood",
    bounds: { minX: -6, maxX: 6, minZ: -6, maxZ: 6 },
    interactables: [
      {
        id: "desk",
        pos: [0, 1, -2],
        label: "Your desk",
        kind: "examine",
        title: "Preliminary notes",
        body: "You can write EIGHT in a hand deliberately larger than usual. Nobody official will ever be obliged to honor it. The file, however it ends, will say eight.",
        radius: 1.8,
      },
      {
        id: "file-eight",
        pos: [2.2, 1, -1.4],
        label: "File the number",
        kind: "use",
        title: "EIGHT",
        body: "Whatever Odell's report eventually says, your own file will say eight. You do not yet know how much that single stubborn digit will matter to a man not yet born.",
        clueId: "eight",
        perception: 5,
        flag: "eight",
        radius: 1.6,
      },
      {
        id: "triplicate",
        pos: [-2.2, 1, -1.4],
        label: "File in triplicate",
        kind: "use",
        title: "In triplicate",
        body: "The clerk stamps without looking. Three copies of a number the town has already decided not to count. One of them, someday, may travel farther than you will.",
        perception: 4,
        flag: "triplicate",
        radius: 1.6,
      },
      {
        id: "coat-hook",
        pos: [4.4, 1.2, 2],
        label: "A plain wool coat",
        kind: "pickup",
        title: "A plain wool coat",
        body: "No badge. Purchased for no better reason than that a dead man's boots looked absurd beneath a police-issue trouser and somehow correct beneath the plain wool. You tell yourself this is procedure.",
        item: "coat-plain",
        perception: 2,
        hideIfExamined: true,
        radius: 1.6,
      },
      {
        id: "leave-precinct",
        pos: [0, 1, 5.4],
        label: "Street",
        kind: "exit",
        exitTo: "street",
        radius: 1.8,
      },
    ],
  },
  {
    id: "almy",
    chapter: 1,
    name: "Mrs. Almy's",
    set: "interior",
    spawn: [0, 1.7, 4],
    fog: "#100e0c",
    fogNear: 8,
    fogFar: 20,
    ambient: "#1a1612",
    iris: "open",
    floor: "wood",
    bounds: { minX: -5, maxX: 5, minZ: -5, maxZ: 5 },
    interactables: [
      {
        id: "almy",
        pos: [0, 1.1, -1.6],
        label: "Mrs. Almy",
        kind: "person",
        radius: 2.2,
        options: [
          {
            id: "badge",
            label: "Ask as the badge",
            requireCoat: "uniform",
            result: {
              lines: [{ text: "SHE LOOKS AT THE BADGE AND NOT AT YOU. THE DOOR DOES NOT OPEN ANY WIDER THAN COURTESY REQUIRES. YOU ARE GIVEN NOTHING AT ALL." }],
              perception: 1,
            },
          },
          {
            id: "plain",
            label: "Ask in the wool coat",
            requireCoat: "plain",
            result: {
              lines: [
                { text: "SHE LOOKS AT THE COAT RATHER THAN THE MAN WEARING IT, AND STEPS ASIDE." },
                { text: "A NAME, AT LAST — NAOMI FREEMAN. SHE HAD COME NORTH LOOKING FIRST FOR A COUSIN, THEN FOR DOCUMENTATION OF WAGES OWED A WHALING ANCESTOR." },
                { text: "A LAY, UNPAID. A SHIP'S NAME SHE REPEATS TWICE BECAUSE SHE CAN SEE YOU DIDN'T CATCH IT THE FIRST TIME." },
                { text: "OPHION." },
                { text: "SHE HAD AN OLDER BOY. DIDN'T COME NORTH WITH HER. EKON. EKON FREEMAN." },
                { text: "YOU WEAR THAT LIKE IT BELONGS TO SOMEBODY ELSE, OFFICER." },
              ],
              clueId: "naomi",
              perception: 10,
              flag: "almy",
            },
          },
        ],
      },
      {
        id: "leave-almy",
        pos: [0, 1, 4.6],
        label: "Street",
        kind: "exit",
        exitTo: "street",
        radius: 1.6,
      },
    ],
  },
  {
    id: "archive",
    chapter: 1,
    name: "Town archive",
    set: "interior",
    spawn: [0, 1.7, 4],
    fog: "#0c0b0a",
    fogNear: 7,
    fogFar: 18,
    ambient: "#12100e",
    iris: "open",
    floor: "wood",
    bounds: { minX: -6, maxX: 6, minZ: -6, maxZ: 6 },
    interactables: [
      {
        id: "ledgers",
        pos: [-2, 1, -2],
        label: "Insurance abstracts",
        kind: "examine",
        title: "Ordinary, well-documented fraud",
        body: "A Wexford estate purchased within eighteen months of a fleet's loss. A Corliss mill acquired the same season. Land bought up by a Pruitt ancestor before the ink on the underwriters' settlement had properly dried.",
        clueId: "insurance",
        perception: 10,
        radius: 1.8,
      },
      {
        id: "crew",
        pos: [2, 1, -2],
        label: "Crew lists",
        kind: "examine",
        title: "Names half-erased by salt",
        body: "Freeman appears once. Then again. Then not at all, the way a name disappears from a ledger not because a man stopped existing but because nobody left cared enough to keep spelling it correctly.",
        perception: 6,
        flag: "crewlist",
        radius: 1.8,
      },
      {
        id: "clerk",
        pos: [0, 1.1, 1],
        label: "Town clerk",
        kind: "person",
        radius: 2,
        options: [
          {
            id: "badge",
            label: "Ask in uniform",
            requireCoat: "uniform",
            result: {
              lines: [{ text: "PROPERTY RECORDS WITHOUT COMPLAINT. TEA WITHOUT BEING ASKED." }],
              perception: 2,
            },
          },
          {
            id: "plain",
            label: "Ask without the badge",
            requireCoat: "plain",
            result: {
              lines: [{ text: "FORTY MINUTES. THE SAME RECORDS. NO TEA." }],
              perception: 2,
            },
          },
        ],
      },
      {
        id: "leave-archive",
        pos: [0, 1, 5.4],
        label: "Street",
        kind: "exit",
        exitTo: "street",
        radius: 1.6,
      },
    ],
  },
  {
    id: "rectory",
    chapter: 1,
    name: "Behind the rectory",
    set: "interior",
    spawn: [0, 1.7, 4],
    fog: "#0e0c0a",
    fogNear: 6,
    fogFar: 18,
    ambient: "#15120f",
    iris: "open",
    floor: "stone",
    bounds: { minX: -5, maxX: 5, minZ: -5, maxZ: 5 },
    interactables: [
      {
        id: "behan",
        pos: [0, 1.1, -1.5],
        label: "Father Behan",
        kind: "person",
        radius: 2.2,
        options: [
          {
            id: "club",
            label: "Ask about the club",
            result: {
              lines: [
                { text: "HE WILL DISCUSS WEXFORD'S TEMPER, FENN'S VANITY, KESSLER'S GRUDGES. HE WILL NOT DISCUSS WHY HE TWICE DECLINED AN INVITATION." },
              ],
              perception: 4,
            },
          },
          {
            id: "name",
            label: "Ask what the name means",
            result: {
              lines: [
                { text: "THEY NAMED THE CLUB AFTER THE SHIP." },
                { speaker: "You", text: "Known." },
                { text: "THEY CAME TO BELIEVE THE SHIP HAD BEEN CHOSEN." },
                { text: "IT WASN'T. MEN INHERIT MONEY AND THEN INVENT A REASON THEY DESERVED IT." },
              ],
              clueId: "ophion-name",
              perception: 8,
              flag: "behan",
            },
          },
        ],
      },
      {
        id: "leave-rectory",
        pos: [0, 1, 4.6],
        label: "Street",
        kind: "exit",
        exitTo: "street",
        radius: 1.6,
      },
    ],
  },
  {
    id: "bar",
    chapter: 1,
    name: "The club bar",
    set: "interior",
    spawn: [0, 1.7, 4],
    fog: "#100c08",
    fogNear: 5,
    fogFar: 16,
    ambient: "#1c1610",
    iris: "open",
    floor: "wood",
    bounds: { minX: -6, maxX: 6, minZ: -6, maxZ: 6 },
    interactables: [
      {
        id: "barman",
        pos: [0, 1.1, -2.2],
        label: "The barman",
        kind: "person",
        radius: 2.2,
        options: [
          {
            id: "badge",
            label: "Drink as Officer Corwin",
            requireCoat: "uniform",
            result: {
              lines: [{ text: "HE CALLS YOU OFFICER CORWIN AND POURS YOU NOTHING YOU HAVEN'T ORDERED." }],
              perception: 1,
            },
          },
          {
            id: "sit",
            label: "Sit still, at the far end",
            requireCoat: "plain",
            result: {
              lines: [
                { text: "HE BEGINS TO TALK NEAR YOU, IF NOT QUITE TO YOU." },
                { text: "SIX MEN MET ON THE LAST THURSDAY OF EVERY MONTH FOR OVER TWO YEARS. FATHER BEHAN WAS INVITED TWICE AND DECLINED BOTH TIMES. KESSLER ONCE CARRIED A PARCEL WRAPPED IN BUTCHER PAPER INTO A PRIVATE ROOM AND LEFT WITHOUT IT." },
                { text: "THE SIXTH MAN NEVER SIGNED A BILL, NEVER ARRIVED BY THE FRONT DOOR, AND WAS NEVER ONCE ASKED TO." },
              ],
              clueId: "six-club",
              perception: 7,
              flag: "barSit",
            },
          },
          {
            id: "her",
            label: "Wait for the refill you didn't ask for",
            requireCoat: "plain",
            requireClue: "six-club",
            result: {
              lines: [
                { text: "THEY STOPPED SPEAKING OF POWER, TOWARD THE END. THEY STARTED SPEAKING, TENDERLY, OF HER." },
                { text: "SHE'LL HAVE US HOME, KESSLER SAID, MORE THAN ONCE. SHE'S NO DIFFERENT FROM ANY MOTHER." },
              ],
              clueId: "maternal",
              perception: 10,
              flag: "barHer",
            },
          },
          {
            id: "pantry",
            label: "Ask after hospitality withdrawn",
            requireFlag: "barHer",
            result: {
              lines: [
                { text: "THERE'S GIN LEFT FROM BEFORE THE WAR. BEHIND THE OLD PANTRY DOOR. THEY BOARDED IT UP DURING A RENOVATION AND NEVER FINISHED UNBOARDING IT." },
                { text: "NOBODY GOES BACK THERE. NOBODY'S GONE BACK THERE IN YEARS." },
              ],
              flag: "pantry",
              unlock: "pantry",
              perception: 4,
            },
          },
        ],
      },
      {
        id: "to-pantry",
        pos: [5, 1, -1],
        label: "The old pantry door",
        kind: "exit",
        exitTo: "pantry",
        requireFlag: "pantry",
        radius: 1.8,
      },
      {
        id: "leave-bar",
        pos: [0, 1, 5.4],
        label: "Street",
        kind: "exit",
        exitTo: "street",
        radius: 1.6,
      },
    ],
  },
  {
    id: "library",
    chapter: 1,
    name: "Fenn's library",
    set: "interior",
    spawn: [0, 1.7, 4],
    fog: "#0c0a08",
    fogNear: 6,
    fogFar: 16,
    ambient: "#16120e",
    iris: "open",
    floor: "wood",
    bounds: { minX: -5, maxX: 5, minZ: -5, maxZ: 5 },
    interactables: [
      {
        id: "ophion-book",
        pos: [0, 1.2, -2],
        label: "An unlocked book",
        kind: "examine",
        title: "A scholarly account",
        body: "A minor and largely discredited figure from old cosmogony: a serpent who ruled, once, before something larger cast him down — not destroyed. Fenn has underlined the passage in a hand that flatters itself. You copy it. You leave the book. Too heavy. Too easily missed.",
        clueId: "book",
        perception: 8,
        radius: 1.8,
      },
      {
        id: "leave-lib",
        pos: [0, 1, 4.6],
        label: "Street",
        kind: "exit",
        exitTo: "street",
        radius: 1.6,
      },
    ],
  },
  {
    id: "room",
    chapter: 1,
    name: "A room above the cobbler",
    set: "interior",
    spawn: [0, 1.7, 3.5],
    fog: "#100e0c",
    fogNear: 4,
    fogFar: 14,
    ambient: "#1a1612",
    iris: "open",
    floor: "wood",
    bounds: { minX: -4.5, maxX: 4.5, minZ: -4.5, maxZ: 4.5 },
    interactables: [
      {
        id: "board",
        pos: [0, 1.4, -3.4],
        label: "The corkboard",
        kind: "use",
        title: "The board",
        body: "It rewards exactly the kind of man you already are. Patient. Methodical. Willing to sit with a fact until it agrees to sit next to another fact. Nothing about the process ever punishes you for using it well.",
        flag: "boardOpened",
        radius: 2.2,
      },
      {
        id: "file-table",
        pos: [2.4, 0.9, -1.2],
        label: "The case file",
        kind: "use",
        title: "The file",
        body: "Statements shift tense. A street number drifts one digit and drifts back. Twice you find a full sentence in your own hand you have no memory of composing. The shape of the report might shift. The report's bones never do.",
        radius: 1.8,
      },
      {
        id: "window",
        pos: [-3.6, 1.4, 0],
        label: "The window",
        kind: "examine",
        title: "Pickman Street",
        body: "A doorway that had always simply existed once your hand found the latch now seems, once or twice, to exist a half-second before your hand arrives.",
        perception: 2,
        radius: 1.6,
      },
      {
        id: "leave-room",
        pos: [0, 1, 4.1],
        label: "Street",
        kind: "exit",
        exitTo: "street",
        radius: 1.6,
      },
    ],
  },
  {
    id: "pantry",
    chapter: 1,
    name: "The boarded pantry",
    set: "interior",
    spawn: [0, 1.7, 3],
    fog: "#090807",
    fogNear: 3,
    fogFar: 12,
    ambient: "#100e0c",
    iris: "open",
    floor: "stone",
    bounds: { minX: -4, maxX: 4, minZ: -4, maxZ: 4 },
    interactables: [
      {
        id: "gin",
        pos: [-1.6, 0.8, -1.2],
        label: "A case of gin",
        kind: "examine",
        title: "Gin from before the war",
        body: "Gone amber with age. You fill the flask here. Your hands are not quite steady. You tell yourself this will be the last time you need luck at all.",
        flag: "refilled",
        radius: 1.6,
      },
      {
        id: "stair",
        pos: [0, 1, -3.2],
        label: "A narrow door, open two inches",
        kind: "exit",
        exitTo: "tunnel",
        radius: 1.8,
      },
      {
        id: "leave-pantry",
        pos: [0, 1, 3.6],
        label: "Back to the bar",
        kind: "exit",
        exitTo: "bar",
        radius: 1.6,
      },
    ],
  },
  {
    id: "tunnel",
    chapter: 1,
    name: "Beneath the estate",
    set: "tunnel",
    spawn: [0, 1.7, 18],
    yaw: Math.PI,
    fog: "#050403",
    fogNear: 2,
    fogFar: 14,
    ambient: "#0a0806",
    iris: "open",
    floor: "stone",
    bounds: { minX: -2.4, maxX: 2.4, minZ: -22, maxZ: 20 },
    walls: [
      { minX: -2.7, maxX: -2.15, minZ: -22, maxZ: 20 },
      { minX: 2.15, maxX: 2.7, minZ: -22, maxZ: 20 },
    ],
    interactables: [
      {
        id: "spill",
        pos: [0, 0.4, 10],
        label: "A spur of rock",
        kind: "examine",
        title: "The flask goes first",
        body: "Torn loose by a spur of rock you never saw coming, gone into the dark below with two soft strikes and then nothing. Finite things run out. The ground has no particular obligation to wait for you to be ready.",
        flag: "spilled",
        perception: 2,
        radius: 1.8,
      },
      {
        id: "sailor",
        pos: [-1.1, 0.5, -2],
        label: "A drowned sailor",
        kind: "examine",
        title: "Wool fused to the shape beneath",
        body: "Bloated the way any drowned thing bloats. They do not look punished. Whatever happened to them happened without moral interest of any kind, the way driftwood is not judged for having drowned, only carried.",
        clueId: "tunnel",
        perception: 6,
        radius: 1.8,
      },
      {
        id: "cultist",
        pos: [1.0, 0.6, -8],
        label: "Something in a dinner jacket",
        kind: "examine",
        title: "A cufflink on a wrist gone the wrong shape",
        body: "These had not simply drowned. Something had gone on happening to them long after drowning should have been the end of the matter. When the lantern touches the face, the eyes open. The cough that comes out is close enough to your mother's that the body decides what it means a half-second before the mind objects.",
        perception: 8,
        flag: "cultistSeen",
        radius: 2,
      },
      {
        id: "up-stair",
        pos: [0, 1, 19.2],
        label: "Back up",
        kind: "exit",
        exitTo: "pantry",
        radius: 1.8,
      },
    ],
    note: "Revolver staggers. Knife staggers longer. Sailors can be finished. Cultists cannot.",
  },
  // Chapter 2
  {
    id: "shore",
    chapter: 2,
    name: "The drowned island",
    set: "island",
    spawn: [0, 1.7, 10],
    fog: "#121416",
    fogNear: 6,
    fogFar: 36,
    ambient: "#1a1c1e",
    iris: "open",
    floor: "stone",
    bounds: { minX: -16, maxX: 16, minZ: -18, maxZ: 14 },
    interactables: [
      {
        id: "first-find",
        pos: [3, 0.4, 2],
        label: "A scrap of scrimshaw",
        kind: "pickup",
        title: "Scrimshaw, salt-eaten",
        body: "A find described and left where the ground kept it proves more than a find carried into a private cabinet. Total recovery. You wrote it in the front of every notebook.",
        perception: 4,
        radius: 1.6,
      },
      {
        id: "observer2",
        pos: [-6, 1.1, -2],
        label: "An Observer, teaching",
        kind: "person",
        radius: 2.2,
        options: [
          {
            id: "watch",
            label: "Do not look directly",
            result: {
              lines: [
                { text: "GRAYSCALE, EXCEPT THE JEWELRY. EXCEPT THE WATER'S REFLECTION." },
                { text: "HE SHOWS SOMEONE YOUNGER WHERE NOT TO PUT A HAND. HE DOES NOT EXPLAIN WHY." },
              ],
              perception: 5,
              flag: "observer2",
            },
          },
        ],
      },
      {
        id: "to-galleries",
        pos: [0, 1, -14],
        label: "Down into the galleries",
        kind: "exit",
        exitTo: "galleries",
        radius: 2.2,
      },
    ],
  },
  {
    id: "galleries",
    chapter: 2,
    name: "The galleries",
    set: "island",
    spawn: [0, 1.7, 8],
    fog: "#101214",
    fogNear: 4,
    fogFar: 22,
    ambient: "#15181a",
    iris: "open",
    floor: "stone",
    bounds: { minX: -10, maxX: 10, minZ: -16, maxZ: 10 },
    interactables: [
      {
        id: "art1",
        pos: [-4, 0.4, 0],
        label: "Ship's hardware",
        kind: "pickup",
        title: "A brass fitting",
        body: "Worth cataloguing. Heavy enough that carrying it means leaving something else.",
        item: "artifact",
        perception: 3,
        radius: 1.5,
      },
      {
        id: "art2",
        pos: [4, 0.4, -4],
        label: "A personal effect",
        kind: "pickup",
        title: "A sailor's comb",
        body: "You can log it and leave it, or take it and spend a slot. The Codex will hold either choice.",
        perception: 3,
        radius: 1.5,
      },
      {
        id: "flask-trace",
        pos: [1, 0.3, -8],
        label: "Something in the silt",
        kind: "examine",
        title: "A corroded flask. A police whistle.",
        body: "Scuff marks that read as a struggle to someone who'd know what a struggle looks like, which you don't. You record that the geometry of the passage should not be possible, and is.",
        perception: 6,
        flag: "walterTrace",
        radius: 1.6,
      },
      {
        id: "to-maw",
        pos: [0, 1, -14],
        label: "Deeper",
        kind: "exit",
        exitTo: "maw",
        radius: 2,
      },
      {
        id: "back-shore",
        pos: [0, 1, 9.2],
        label: "Back toward the shore",
        kind: "exit",
        exitTo: "shore",
        radius: 1.8,
      },
    ],
  },
  {
    id: "maw",
    chapter: 2,
    name: "The maw",
    set: "tunnel",
    spawn: [0, 1.7, 10],
    fog: "#08090a",
    fogNear: 1.5,
    fogFar: 12,
    ambient: "#0c0e10",
    iris: "wide",
    floor: "stone",
    bounds: { minX: -2.2, maxX: 2.2, minZ: -18, maxZ: 12 },
    interactables: [
      {
        id: "wrong-stone",
        pos: [0, 0.4, 0],
        label: "Stone that feels wrong",
        kind: "examine",
        title: "A passage under open ocean",
        body: "You can only record, in your own hand, that it should not be possible and is. You do not know whose cellar waits at the other end.",
        perception: 8,
        flag: "wrongGeometry",
        radius: 2,
      },
      {
        id: "dead-ahead",
        pos: [0, 0.6, -10],
        label: "Light ahead that is not yours",
        kind: "examine",
        title: "They are correct",
        body: "The Observers are not primitive. Curiosity is not rewarded here. To know the horror is to succumb to it. You dug because you wanted meaning. You understand because you can no longer stop yourself.",
        perception: 12,
        flag: "mawSeen",
        radius: 2.2,
      },
    ],
  },
  // Chapter 3
  {
    id: "voss",
    chapter: 3,
    name: "Adrian Voss, attorney",
    set: "office",
    spawn: [0, 1.7, 4],
    fog: "#12100e",
    fogNear: 8,
    fogFar: 18,
    ambient: "#1a1612",
    iris: "open",
    floor: "wood",
    bounds: { minX: -5, maxX: 5, minZ: -5, maxZ: 5 },
    interactables: [
      {
        id: "voss-man",
        pos: [0, 1.1, -2],
        label: "Voss",
        kind: "person",
        radius: 2.2,
        options: [
          {
            id: "lay",
            label: "Ask for the book he's still holding",
            result: {
              lines: [
                { speaker: "Voss", text: "The lay. Wages owed a dead whaler off a ship that hasn't existed in a hundred-odd years. You understand there's no court in this county that opens that book again." },
                { speaker: "You", text: "I understand you're still holding the book. That's the part I came about." },
              ],
              clueId: "insurance",
              perception: 4,
              flag: "vossTalk",
              item: "wage-claim",
            },
          },
        ],
      },
      {
        id: "to-town3",
        pos: [0, 1, 4.6],
        label: "Out",
        kind: "exit",
        exitTo: "town3",
        radius: 1.6,
      },
    ],
  },
  {
    id: "town3",
    chapter: 3,
    name: "Widow's Bight, 1940s",
    set: "street",
    spawn: [0, 1.7, 4],
    fog: "#121416",
    fogNear: 6,
    fogFar: 28,
    ambient: "#181a1c",
    iris: "open",
    floor: "gravel",
    bounds: { minX: -14, maxX: 14, minZ: -8, maxZ: 10 },
    interactables: [
      {
        id: "file-found",
        pos: [3, 1, -4],
        label: "A case file that should not be here",
        kind: "examine",
        title: "Officer Corwin's original file",
        body: "Unreliable in its presentation. True in its substance. How it reached you is not recorded. It says eight.",
        item: "walter-file",
        perception: 6,
        radius: 1.8,
      },
      {
        id: "book3",
        pos: [-4, 1, -4],
        label: "A book from a dead archaeologist's effects",
        kind: "examine",
        title: "Ophion",
        body: "A primordial serpent who ruled before being overthrown and cast down, not destroyed. Two hands in the margin: one flattering a delusion, one chasing the question honestly. No one tells you which is which. No one tells you what the club was named for.",
        item: "ophion-book",
        perception: 8,
        flag: "ophionRead",
        radius: 1.8,
      },
      {
        id: "to-cavern",
        pos: [0, 1, 8],
        label: "The island path",
        kind: "exit",
        exitTo: "cavern",
        radius: 2,
      },
    ],
  },
  {
    id: "cavern",
    chapter: 3,
    name: "The caverns",
    set: "cavern",
    spawn: [0, 1.7, 14],
    fog: "#070605",
    fogNear: 2,
    fogFar: 16,
    ambient: "#0b0a08",
    iris: "open",
    floor: "stone",
    bounds: { minX: -3, maxX: 3, minZ: -24, maxZ: 16 },
    interactables: [
      {
        id: "ward-remains",
        pos: [1.2, 0.4, 2],
        label: "Remains, and a Codex",
        kind: "examine",
        title: "Ward Kohistani",
        body: "You are the only person who will ever validate that he existed and reached as far as he did. The moment is private. Neither of you gets to share it.",
        item: "codex",
        perception: 6,
        flag: "foundWard",
        radius: 1.8,
      },
      {
        id: "charges",
        pos: [-1, 0.4, -6],
        label: "Charges",
        kind: "pickup",
        title: "Demolition charges",
        body: "Rubble and walls are a delay, not protection. Nothing built to stop a man can stop what is down here. Still: you came trained, and training wants a job.",
        item: "charges",
        radius: 1.6,
      },
      {
        id: "abyss",
        pos: [0, 1, -20],
        label: "The abyss",
        kind: "exit",
        exitTo: "abyss",
        radius: 2.2,
      },
    ],
  },
  {
    id: "abyss",
    chapter: 3,
    name: "No further",
    set: "cavern",
    spawn: [0, 1.7, 6],
    fog: "#030201",
    fogNear: 1,
    fogFar: 10,
    ambient: "#080604",
    iris: "burn",
    floor: "stone",
    bounds: { minX: -4, maxX: 4, minZ: -8, maxZ: 8 },
    interactables: [
      {
        id: "final",
        pos: [0, 1, -3],
        label: "One action, while you are still yourself",
        kind: "use",
        title: "Still yourself",
        body: "Sealing something. Placing the ledger where it might someday surface. Choosing what evidence burns. It cannot save you. It will define you.",
        flag: "finalReady",
        radius: 2.4,
      },
    ],
  },
];

export const LOCATION = Object.fromEntries(LOCATIONS.map((l) => [l.id, l])) as Record<string, LocationDef>;

export const CHAPTER_META = [
  {
    id: 1 as const,
    year: "1923",
    title: "No Exit Wound",
    name: "Walter Corwin",
    role: "Beat cop",
    verb: "Investigate",
    coping: "A flask. It does what it claims.",
  },
  {
    id: 2 as const,
    year: "193_",
    title: "The Maw",
    name: "Ward Kohistani",
    role: "Archaeologist",
    verb: "Recover",
    coping: "Field-grade opium. Honest, finite.",
  },
  {
    id: 3 as const,
    year: "1940s",
    title: "Ophion",
    name: "Ekon Freeman",
    role: "Veteran",
    verb: "Demand",
    coping: "Cigarettes never run out. Matches do.",
  },
];

export const ACHIEVEMENTS = {
  died: {
    title: "Died",
    desc: "Corwin, Walter. Disappeared under personal strain following an unresolved accident at the Ophion Club. Replacement file records six names.",
  },
  diedAgain: {
    title: "Died Again",
    desc: "Kohistani, Ward. Lost in the depths of the drowned island. Society correspondence lists the posting as unproductive. Remains unclaimed by the Society.",
  },
  diedKnowing: {
    title: "Died Knowing",
    desc: "Freeman, Ekon. Reached the abyss and understood it. Comprehension preceded collapse. Collapse killed him. No exception is recorded.",
  },
};
